{
  "workdir": "/users/sdevries/hashserver-test",
  "hostname": "mbi-frontend",
  "key": 'hashserver-mbi-{workdir.strip("/").replace("/", "--")}',
  "command": "hashserver --port-range {port_start} {port_end} --status-file {status_file} --host {config['network_interface']} --timeout {timeout} {workdir}",
  "network_interface": "0.0.0.0",
  "handshake": "healthcheck",
  "conda": "hashserver",
  "timeout": 600,
  "port_start": 60001,
  "port_end": 61000,
}
